import { createElement } from 'react';
import { act, create } from 'react-test-renderer';
import { afterEach, expect, test, vi } from 'vitest';
import RoundNavigator, { nextUnanswered } from '../src/components/RoundNavigator';
import BracketBoard from '../src/components/BracketBoard';
import { generateSeededBracket } from '../src/lib/standardBracket';
import { blankPrediction, applyPicks } from '../src/lib/customScoring';
let tree;
afterEach(() => { if (tree) act(() => tree.unmount()); tree = null; });
test('next unanswered skips decided matches, byes and unavailable feeders and wraps', () => {
  const rounds = [[{id:'a',ready:true,answered:true},{id:'bye',ready:false,answered:true},{id:'b',ready:true,answered:false}], [{id:'final',ready:false,answered:false}]];
  expect(nextUnanswered(rounds,null)?.id).toBe('b');
  expect(nextUnanswered(rounds,'b')?.id).toBe('b');
  rounds[0][2].answered=true;
  expect(nextUnanswered(rounds,'b')).toBe(null);
  rounds[1][0].ready=true;
  expect(nextUnanswered(rounds,'b')).toMatchObject({id:'final',round:1});
});
test('overview preserves round choice; next unanswered switches round and focuses the card', () => {
  const focus=vi.fn(), scrollIntoView=vi.fn();
  const rounds=[[{id:'a',ready:true,answered:true}],[{id:'b',ready:true,answered:false}]];
  const children=({roundProps,matchProps})=>rounds.map((round,r)=>createElement('div',{key:r,...roundProps(r)},round.map(m=>createElement('div',{key:m.id,...matchProps(m.id)}))));
  act(()=>{tree=create(createElement(RoundNavigator,{rounds},children),{createNodeMock:el=>el.type==='section'?{querySelectorAll:()=>[{dataset:{mobileMatch:'b'},focus,scrollIntoView}]}:null});});
  const button=text=>tree.root.findAllByType('button').find(b=>b.children.includes(text));
  act(()=>button('Full bracket overview').props.onClick());
  expect(tree.root.findByType('section').props.className).toContain('round-overview');
  act(()=>button('Next unanswered').props.onClick());
  expect(tree.root.findByType('select').props.value).toBe(1);
  expect(tree.root.findByType('section').props.className).toContain('round-cards');
  expect(focus).toHaveBeenCalledTimes(1);
  act(()=>button('Next unanswered').props.onClick());
  expect(focus).toHaveBeenCalledTimes(2);
  act(()=>button('Full bracket overview').props.onClick());
  act(()=>button('Matchup cards').props.onClick());
  expect(tree.root.findByType('select').props.value).toBe(1);
});
test('shared board preserves pick identity, scores, and selection through overview toggles',()=>{
  const state=blankPrediction(generateSeededBracket(['A','B','C','D'])), pick=vi.fn();
  const sc={editable:true,get:()=>'',change:vi.fn(),blur:vi.fn()};
  act(()=>{tree=create(createElement(BracketBoard,{state,nameMap:{},editable:true,onPick:pick,sc}));});
  const choice=tree.root.findAllByProps({role:'button'})[0];
  act(()=>choice.props.onClick());
  const [id,pid]=pick.mock.calls[0];
  expect(state.rounds[0]).toContain(id);
  const selected=applyPicks(state,{[id]:pid});
  act(()=>tree.update(createElement(BracketBoard,{state:selected,nameMap:{},editable:true,onPick:pick,sc})));
  expect(tree.root.findAllByProps({'aria-pressed':true,role:'button'})).toHaveLength(1);
  const toggle=()=>tree.root.findAllByType('button').find(b=>typeof b.props['aria-pressed']==='boolean');
  act(()=>toggle().props.onClick());act(()=>toggle().props.onClick());
  expect(tree.root.findAllByProps({'aria-pressed':true,role:'button'})).toHaveLength(1);
  const score=tree.root.findAllByType('input')[0];
  act(()=>score.props.onChange({target:{value:'3'}}));
  expect(sc.change).toHaveBeenCalledWith(expect.any(String),expect.any(String),'3');
});
test('read-only boards omit next unanswered and cannot pick winners',()=>{
  act(()=>{tree=create(createElement(BracketBoard,{state:generateSeededBracket(['A','B']),nameMap:{},editable:false}));});
  expect(tree.root.findAllByProps({role:'button'})).toHaveLength(0);
  expect(tree.root.findAllByType('button').some(b=>b.children.includes('Next unanswered'))).toBe(false);
});
